// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'default': string;
  'fullsize': string;
  'link': string;
  'primary': string;
  'root': string;
  'secondary': string;
  'small': string;
}
export const cssExports: CssExports;
export default cssExports;
