// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  shimmer: string;
  skeleton_box: string;
}
export const cssExports: CssExports;
export default cssExports;
