// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bug: string;
  dark: string;
  dragon: string;
  electric: string;
  fairy: string;
  fighting: string;
  fire: string;
  flying: string;
  ghost: string;
  gradient_bug: string;
  gradient_dark: string;
  gradient_dragon: string;
  gradient_electric: string;
  gradient_fairy: string;
  gradient_fighting: string;
  gradient_fire: string;
  gradient_flying: string;
  gradient_ghost: string;
  gradient_grass: string;
  gradient_ground: string;
  gradient_ice: string;
  gradient_normal: string;
  gradient_poison: string;
  gradient_psychic: string;
  gradient_rock: string;
  gradient_steel: string;
  gradient_water: string;
  grass: string;
  ground: string;
  ice: string;
  normal: string;
  poison: string;
  psychic: string;
  rock: string;
  shimmer: string;
  skeleton_box: string;
  steel: string;
  water: string;
}
export const cssExports: CssExports;
export default cssExports;
