// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  attack: string;
  defense: string;
  hp: string;
  skeleton_value: string;
  statItem: string;
  statValue: string;
  statWrap: string;
}
export const cssExports: CssExports;
export default cssExports;
