// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  skeleton_title: string;
  titleText: string;
}
export const cssExports: CssExports;
export default cssExports;
