// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  childWrapper: string;
  comeInOut: string;
  sparkleSvg: string;
  sparkleWrapper: string;
  spin: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
