// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  ability: string;
  idBadge: string;
  infoGen: string;
  infoHead: string;
  infoName: string;
  infoStats: string;
  infoWrap: string;
  labelWrap: string;
  leftWrap: string;
  pictureWrap: string;
  resources: string;
  root: string;
  statWrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
