// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  pictureWrap: string;
  root: string;
  stats_wrapper: string;
  titleName: string;
}
export const cssExports: CssExports;
export default cssExports;
