// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  attack: string;
  defense: string;
  hp: string;
  infoWrap: string;
  label: string;
  labelWrap: string;
  pictureWrap: string;
  root: string;
  shimmer: string;
  skeleton_box: string;
  skeleton_label: string;
  skeleton_title: string;
  skeleton_value: string;
  statItem: string;
  statValue: string;
  statWrap: string;
  titleName: string;
}
export const cssExports: CssExports;
export default cssExports;
