// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  card: string;
  infoWrap: string;
  root: string;
}
export const cssExports: CssExports;
export default cssExports;
