// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  code: string;
  root: string;
  text: string;
}
export const cssExports: CssExports;
export default cssExports;
