// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  filters: string;
  filters_dropdown: string;
}
export const cssExports: CssExports;
export default cssExports;
