// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  contentWrap: string;
  description: string;
  filters: string;
  layerWrap: string;
  root: string;
  search: string;
}
export const cssExports: CssExports;
export default cssExports;
